### ISSUE TITLE
Feature: Crowdfunding

### ISSUE THREAD

**Issue by nadrummond** [n3oltd/N3O.Umbraco#375]
We have the concept of:

**Campaigns**

**Fundraisers**

**Teams**

## Roadmap

```[tasklist]
### Tasks
- [ ] https://github.com/n3oltd/N3O.Umbraco/issues/379
- [ ] https://github.com/n3oltd/N3O.Umbraco/issues/376
- [ ] https://github.com/n3oltd/N3O.Umbraco/issues/377
- [ ] https://github.com/n3oltd/N3O.Umbraco/issues/378
- [ ] https://github.com/n3oltd/N3O.Umbraco/issues/380
- [ ] https://github.com/n3oltd/N3O.Umbraco/issues/381
- [ ] https://github.com/n3oltd/N3O.Umbraco/issues/382
- [ ] https://github.com/n3oltd/N3O.Umbraco/issues/383
- [ ] https://github.com/n3oltd/N3O.Umbraco/issues/400
- [ ] https://github.com/n3oltd/client-onboarding/issues/71
- [ ] https://github.com/n3oltd/N3O.Umbraco/issues/407
```
